

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

import MovieCarousel from "@/components/homepage/movieCarousel/MovieCarousel";
import Trends from "@/components/homepage/trends/Trends";
import CookieConsent from "@/components/global/cookieConsent/CookieConsent";
import { Metadata } from "next";
import PopularMovies from "@/components/homepage/popularMovies/PopularMovies";
import { getMovies, getTvShows } from "@/utils/api";
import PopularMoviesClient from "@/components/homepage/popularMovies/PopularMoviesClient";
import GoldenGlobeAwards from "@/components/homepage/goldenGlobaAwards/GoldenGlobeAwards";
import Series from "@/components/homepage/series/Series";
import Suggestions from "@/components/homepage/suggestions/Suggestions";
import Collections from "@/components/homepage/collections/Collections";



config.autoAddCss = false;


const metadata: Metadata = {
    title: "MovieApp on Next.js",
    description: "Generated by create next app",
};

export default async function Home() {

    let moviesRespSlider;
    let moviesRespPopular
    let moviesRespTrends
    let moviesRespGolden
    let tvShowsResp


    let trends
    let popular
    let slider
    let golden
    let tvSeries;

    let total
    let moviesResp
    try {
        moviesRespSlider = await getMovies({
            category: 'Drama',
            orderBy: 'asc',
            limit: 3
        });

        slider = moviesRespSlider.data || [];




        moviesRespPopular = await getMovies({
            // year: 2022,
            orderBy: 'desc'
        });
        popular = moviesRespPopular.data || [];



        moviesRespTrends = await getMovies({
            year: 2022,

            orderBy: 'asc'
        });
        trends = moviesRespTrends.data || [];
        total = moviesResp?.total || 0;



        moviesRespGolden = await getMovies({
            year: 2025,

            orderBy: 'asc'
        });
        golden = moviesRespGolden.data || [];
        total = moviesResp?.total || 0;
        // console.log(moviesResp)


        tvShowsResp = await getTvShows({

        });

        tvSeries = tvShowsResp.data || [];

    } catch (err) {
        console.error('getMovies error', err);
        moviesResp = [];
    }

    return (
        <>
            <MovieCarousel movies={slider} />
            <div className="trends ">
                <Trends movies={trends} />
            </div>

            <section className="popular-movies ">
                <PopularMoviesClient popularMovies={popular} />
            </section >

            <section className="golden-awards ">
                <GoldenGlobeAwards moviesGolden={golden} />
            </section >


            <section className="tv-series ">
                <Series tvSeries={tvSeries} />
            </section >



            <section className="suggestions ">
                <Suggestions />
            </section >

            <section>
                <Collections />
            </section>
        </>
    )
}