

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

import MovieCarousel from "@/components/homepage/movieCarousel/MovieCarousel";
import Trends from "@/components/homepage/trends/Trends";
import CookieConsent from "@/components/global/cookieConsent/CookieConsent";

import { Metadata } from "next";
import PopularMovies from "@/components/homepage/popularMovies/PopularMovies";

import { getMovies } from "@/utils/api";
import PopularMoviesClient from "@/components/homepage/popularMovies/PopularMoviesClient";



config.autoAddCss = false;


const metadata: Metadata = {
    title: "MovieApp on Next.js",
    description: "Generated by create next app",
};

export default async function Home() {

    let moviesRespSlider;
    let moviesRespPopular
    let moviesRespTrends

    let trends
    let popular
    let slider

    let total
    let moviesResp
    try {
        moviesRespSlider = await getMovies({
            category: 'Drama',
            orderBy: 'asc'
        });

        slider = moviesRespSlider.data || [];




        moviesRespPopular = await getMovies({
            // year: 2022,
            orderBy: 'desc'
        });
        popular = moviesRespPopular.data || [];



        moviesRespTrends = await getMovies({
            year: 2022,

            orderBy: 'asc'
        });
        trends = moviesRespTrends.data || [];

        total = moviesResp.total || 0;
        // console.log(moviesResp)
    } catch (err) {
        console.error('getMovies error', err);
        moviesResp = [];
    }

    return (
        <>
            <MovieCarousel movies={slider} />
            <div className="trends ">
                <Trends movies={trends} />
            </div>

            <section className="popular-movies ">
                <PopularMoviesClient popularMovies={popular} />
            </section >

        </>
    )
}