---
apiVersion: v1
kind: Service
metadata:
  name: api-k8s
  namespace: nestjs-movie
spec:
  selector:
    app: api-k8s
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-k8s
  namespace: nestjs-movie
  labels:
    app: api-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-k8s
  template:
    metadata:
        labels:
         app: api-k8s
    spec:
      serviceAccountName: default   
      containers:
        - name: api-k8s
          image: rustamdev/api-k8s:0.1
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: development
          ports:
            - containerPort: 3000