import { Metadata } from "next";
import { ErrorWrapper } from "./error-wrapper";

export const metadata: Metadata = {
  title: {
    default: "My Site",
    template: "%s | Unique",

    absolute: "",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>Header</header>
        <ErrorWrapper>{children}</ErrorWrapper>
        <footer>Footer</footer>
      </body>
    </html>
  );
}
