name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:14
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: testdb
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        env:
            DATABASE_URL: "postgres://postgres:postgres@localhost:5432/testDb"
            JWT_SECRET: "testJWT"
            NODE_ENV: test
            BASE_URL: http://localhost:3001

        steps:

        

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"


            - name: Enable pnpm
              run: |
                corepack enable 
                corepack prepare pnpm@9.15.0 --activate
                
            - name: Install Frontend dependencies
              working-directory: ./next
              run: pnpm install

            - name: Install Backend dependencies
              working-directory: ./api
              run: pnpm install





            - name: Wait for PostgreSQL
              run: |
                  timeout 30s bash -c 'until pg_isready -h localhost -p 5432; do sleep 1; done'
              env:
                  PGHOST: localhost
                  PGPORT: 5432
                  PGUSER: postgres
                  PGPASSWORD: postgres

            - name: Generate Prisma Client
              # working-directory: ./next
              env:
                  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/testdb"
              run: npx prisma generate --schema=api/libs/prisma/schema.prisma

            - name: Run database migrations
              # working-directory: ./next
              env:
                  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/testdb"
              run: npx prisma migrate deploy --schema=api/ibs/prisma/schema.prisma

            # - name: Build application
            #   working-directory: ./next
            #   run: npm run build-full

            - name: Run format
              working-directory: ./next
              run: npm run format

